import * as Books from './books';
import * as Controllers from './controllers';
import * as Cv from './cv';
import * as Dto from './dto';
import * as Iservices from './iservices';
import * as Job from './job';
import * as Microsoft from './microsoft';
import * as Model from './model';
import * as Profile from './profile';
import * as Services from './services';
export * from './api-config.service';
export { Books, Controllers, Cv, Dto, Iservices, Job, Microsoft, Model, Profile, Services };
